name = "my-worker"
main = "src/worker.ts"
compatibility_date = "2024-08-06"
account_id = "42aaeb058deccdcc3e1052d4fc4f186c"
workers_dev = false

# Needed for crypto.randomUUID()
# Using node_compat = true does not work?
compatibility_flags = ["nodejs_compat"]

# [[r2_buckets]]
# binding = 'R2_STORAGE_BUCKET'
# bucket_name = 'echoes-social'
